feature ssh connection
dasshboard/dasshboard-server pull request #4
Opened 2023-03-20 18:32 UTC by Zaher1307

2023-03-20 19:14 UTC, IslamWalid requested changes

2023-03-20 19:17 UTC, IslamWalid commented on src/services/ssh.js
> +        reject(err);
you need to return in the `if-statement`

2023-03-20 19:19 UTC, IslamWalid commented on src/services/ssh.js
> +        reject(err);
you need to create an error handler module to handle the errors in the connecting process

2023-03-20 19:20 UTC, Zaher1307 commented on src/services/ssh.js
> +        reject(err);
Ok, I fixed it

2023-03-20 19:24 UTC, IslamWalid commented on src/services/ssh.js
> +        reject(err);
It's a good style to add an extra space between the error handling `if` statement and the rest of the code.

2023-03-20 19:36 UTC, IslamWalid commented on src/services/ssh.js
> +      }
It's a good style to add an empty line between the error handling if statement and the rest of the code.

2023-03-20 19:48 UTC, Zaher1307 commented on src/services/ssh.js
> +      }
I fixed it

2023-03-20 19:48 UTC, Zaher1307 commented on src/services/ssh.js
Ok, I did it

2023-03-21 10:31 UTC, meldisoukyy approved these changes
Awesome!

2023-03-21 13:01 UTC, meldisoukyy approved these changes

2023-03-21 13:01 UTC, meldisoukyy commented on src/services/ssh.js
> +        resolve(result || error);
I think it is better to distinguish between the result and the error

2023-03-21 13:07 UTC, meldisoukyy requested changes

2023-03-21 13:07 UTC, meldisoukyy commented on app.js
> +const sshRoute = require('./src/routes/ssh');
you have to change the path of `sshRoute` to be `'./src/services/ssh'`,
and it's better to rename `sshRoute` to be `sshService` for example.

2023-03-21 13:07 UTC, meldisoukyy commented on src/services/ssh.js
> +        resolve(result || error);
I think it's better to distinguish between the result and the error.

2023-03-21 16:11 UTC, IslamWalid requested changes

2023-03-21 16:16 UTC, IslamWalid requested changes

2023-03-21 16:16 UTC, IslamWalid commented on app.js
> +const sshRoute = require('./src/routes/ssh');
`ssh` won't be a route at all, it's just a service. There's no need to add it as a route in the app in the first place

2023-03-22 12:03 UTC, Zaher1307 commented on src/services/ssh.js
> +        resolve(result || error);
do you have any suggestions?

2023-03-22 12:12 UTC, Zaher1307 commented on src/services/ssh.js
> +function connect(config) {
I think there is not the right place to check for errors, for example, if I have a controller to connect it should check first for all credentials

2023-03-22 12:15 UTC, Zaher1307 commented on app.js
> +const sshRoute = require('./src/routes/ssh');
yes it's a mistake I had a module to test the service then I forget to remove app.js and index.js

2023-03-22 12:15 UTC, Zaher1307 commented on src/services/ssh.js
> +const { Client } = require('ssh2');
ok it's my next sprint

2023-03-22 12:17 UTC, Zaher1307 commented on src/services/ssh.js
> +    conn.exec(cmd, (err, stream) => {
Done

2023-03-22 14:18 UTC, meldisoukyy commented on src/services/ssh.js
> +        resolve(result || error);
you may resolve an object like this {type: "result"| "error", content: result|error}

2023-03-22 15:15 UTC, Zaher1307 commented on src/services/ssh.js
> +        resolve(result || error);
nice, I made a similar solution

2023-03-22 15:30 UTC, meldisoukyy approved these changes

2023-03-23 21:55 UTC, Zaher1307 commented
I have found a wrapper package doing what I need.
the package called [`node-ssh`](https://www.npmjs.com/package/node-ssh)

2023-03-23 21:55 UTC, closed without merging