build: ssh connection middleware and authenticate middleware
dasshboard/dasshboard-server pull request #7
Opened 2023-05-06 14:55 UTC by Zaher1307

2023-05-06 16:15 UTC, IslamWalid commented on src/middlewares/vm-connection.js
> +const { NodeSSH } = require('node-ssh');
this file is better named with the name of the function it exposes, `vm-connect` is a better name.

2023-05-06 16:15 UTC, IslamWalid commented on src/middlewares/vm-connection.js
> +    next(err);
you need - if applicable - to create an error handler module for any expected errors from the ssh connection.

2023-05-06 16:15 UTC, IslamWalid commented on src/utils/validate-credentials.js
> +const { ResponseMessages } = require('./enums');
I think it's better to use general input validator

2023-05-07 20:09 UTC, meldisoukyy approved these changes

2023-05-07 20:20 UTC, Eslam-Nawara commented on src/middlewares/vm-connection.js
> +    sendResErr(res, {
You should return just after sending the response and not carry on executing the function.

2023-05-07 20:32 UTC, Eslam-Nawara requested changes

2023-05-07 20:32 UTC, Eslam-Nawara commented on src/middlewares/vm-connection.js
> +    sendResErr(res, {
You should return just after sending the response and not carry on executing the function.

2023-05-07 20:32 UTC, Eslam-Nawara commented on src/middlewares/vm-connection.js
> +      message: ResponseMessages.MISSING_FIELDS
It would be better to use the returned ` message ` constant instead of duplicating ` ResponseMessage...`

2023-05-09 09:38 UTC, Eslam-Nawara approved these changes

2023-05-09 09:40 UTC, merged